sudo: required

language: python
python: 2.7

services:
  - docker

env:
  - TOX_ENV=py27

git:
  submodules: false

before_install:
  - GALAXY_TRAVIS_USER=galaxy
  - GALAXY_UID=1450
  - GALAXY_GID=1450
  - GALAXY_HOME=/home/galaxy
  - GALAXY_USER=admin@galaxy.org
  - GALAXY_USER_EMAIL=admin@galaxy.org
  - GALAXY_USER_PASSWD=admin
  - BIOBLEND_GALAXY_API_KEY=admin
  - BIOBLEND_GALAXY_URL=http://localhost:8080

  - git submodule update --init --recursive
  - sudo groupadd -r $GALAXY_TRAVIS_USER -g $GALAXY_GID
  - sudo useradd -u $GALAXY_UID -r -g $GALAXY_TRAVIS_USER -d $GALAXY_HOME -p travis_testing -c "Galaxy user" $GALAXY_TRAVIS_USER
  - sudo mkdir $GALAXY_HOME
  - sudo chown -R $GALAXY_TRAVIS_USER:$GALAXY_TRAVIS_USER $GALAXY_HOME
  - cd galaxy && docker build -t galaxy-docker/test .
  - |
    docker run -d -p 8080:80 \
    -e GALAXY_CONFIG_ALLOW_USER_DATASET_PURGE=True \
    -e GALAXY_CONFIG_ALLOW_LIBRARY_PATH_PASTE=True \
    -e GALAXY_CONFIG_ENABLE_USER_DELETION=True \
    -e GALAXY_CONFIG_ENABLE_BETA_WORKFLOW_MODULES=True \
    -v /tmp/:/tmp/ \
    galaxy-docker/test
  - docker ps
  - cd $GALAXY_HOME
  - sudo su $GALAXY_TRAVIS_USER -c 'wget https://github.com/galaxyproject/bioblend/archive/v0.7.0.tar.gz'
  - sudo su $GALAXY_TRAVIS_USER -c 'tar xfz v0.7.0.tar.gz'

install:
  - cd $GALAXY_HOME/bioblend-0.7.0
  - sudo su $GALAXY_TRAVIS_USER -c 'python setup.py install --user'
  - sudo su $GALAXY_TRAVIS_USER -c 'pip install --user --upgrade "tox>=1.8.0"'

script:
  - curl --fail $BIOBLEND_GALAXY_URL/api/version
  # Run bioblend nosetests with the same UID and GID as the galaxy user inside if Docker
  # this will guarantee that exchanged files bewteen bioblend and Docker are read & writable from both sides
  - sudo -E su $GALAXY_TRAVIS_USER -c "export PATH=$GALAXY_HOME/.local/bin/:$PATH && cd $GALAXY_HOME/bioblend-0.7.0 && tox -e $TOX_ENV"
  # Test the 'old' tool installation script
  - docker run galaxy-docker/test bash -c 'install-repository "--url https://toolshed.g2.bx.psu.edu -o iuc --name bedtools --panel-section-name 'BEDTools'"'
  # Test the 'new' tool installation script
  - docker run galaxy-docker/test bash -c "install-tools $GALAXY_HOME/ansible/galaxy-tools-playbook/files/tool_list.yaml"
